SELECT 
    NUMERO_RECLAMO,
    FECHA_REGISTRO,
    CLIENTE,
    ESTADOWORKFLOW,
    RESULTADO,
    FECHACIERRE,
    DESCRIPCION,
    INFORMACION_RESULTADO,
    SUPERVISORSOLUCIONADOR,
    NOMBRESOLUCIONADOR,
    FAMILIA,
    NUMERODOCUMENTO,
    PRODUCTO,
    TIPOLOGIA,
    '2020' AS AÑO_ORIGEN,
    'Vista_Reclamos_2020.xlsx' AS ARCHIVO_ORIGEN
FROM Vista_2020

UNION ALL

SELECT 
    NUMERO_RECLAMO,
    FECHA_REGISTRO,
    CLIENTE,
    ESTADOWORKFLOW,
    RESULTADO,
    FECHACIERRE,
    DESCRIPCION,
    INFORMACION_RESULTADO,
    SUPERVISORSOLUCIONADOR,
    NOMBRESOLUCIONADOR,
    FAMILIA,
    NUMERODOCUMENTO,
    PRODUCTO,
    TIPOLOGIA,
    '2021' AS AÑO_ORIGEN,
    'Vista_Reclamos_2021.xlsx' AS ARCHIVO_ORIGEN
FROM Vista_2021

UNION ALL

SELECT 
    NUMERO_RECLAMO,
    FECHA_REGISTRO,
    CLIENTE,
    ESTADOWORKFLOW,
    RESULTADO,
    FECHACIERRE,
    DESCRIPCION,
    INFORMACION_RESULTADO,
    SUPERVISORSOLUCIONADOR,
    NOMBRESOLUCIONADOR,
    FAMILIA,
    NUMERODOCUMENTO,
    PRODUCTO,
    TIPOLOGIA,
    '2022' AS AÑO_ORIGEN,
    'Vista_Reclamos_2022.xlsx' AS ARCHIVO_ORIGEN
FROM Vista_2022

UNION ALL

SELECT 
    NUMERO_RECLAMO,
    FECHA_REGISTRO,
    CLIENTE,
    ESTADOWORKFLOW,
    RESULTADO,
    FECHACIERRE,
    DESCRIPCION,
    INFORMACION_RESULTADO,
    SUPERVISORSOLUCIONADOR,
    NOMBRESOLUCIONADOR,
    FAMILIA,
    NUMERODOCUMENTO,
    PRODUCTO,
    TIPOLOGIA,
    '2023' AS AÑO_ORIGEN,
    'Vista_Reclamos_2023.xlsx' AS ARCHIVO_ORIGEN
FROM Vista_2023

UNION ALL

SELECT 
    NUMERO_RECLAMO,
    FECHA_REGISTRO,
    CLIENTE,
    ESTADOWORKFLOW,
    RESULTADO,
    FECHACIERRE,
    DESCRIPCION,
    INFORMACION_RESULTADO,
    SUPERVISORSOLUCIONADOR,
    NOMBRESOLUCIONADOR,
    FAMILIA,
    NUMERODOCUMENTO,
    PRODUCTO,
    TIPOLOGIA,
    '2024' AS AÑO_ORIGEN,
    'Vista_Reclamos_2024.xlsx' AS ARCHIVO_ORIGEN
FROM Vista_2024

UNION ALL

SELECT 
    NUMERO_RECLAMO,
    FECHA_REGISTRO,
    CLIENTE,
    ESTADOWORKFLOW,
    RESULTADO,
    FECHACIERRE,
    DESCRIPCION,
    INFORMACION_RESULTADO,
    SUPERVISORSOLUCIONADOR,
    NOMBRESOLUCIONADOR,
    FAMILIA,
    NUMERODOCUMENTO,
    PRODUCTO,
    TIPOLOGIA,
    '2025' AS AÑO_ORIGEN,
    'Vista_Reclamos_2025.xlsx' AS ARCHIVO_ORIGEN
FROM Vista_2025;